[colors.primary]
    background = "#222222"
[font]
    normal = { family = "Hack Nerd Font Mono", style = "Regular"}
    bold = { family = "Hack Nerd Font Mono", style = "Regular"}
    italic = { family = "Hack Nerd Font Mono", style = "Regular"}
    bold_italic = { family = "Hack Nerd Font Mono", style = "Regular"}
    size = 12

[window]
    opacity = 0.95

[terminal]
shell = "fish"
