#!/bin/bash

directory=~/Pictures/Anime/Honkai_Impact/Widescreen
laptop="eDP-1"
external="HDMI-A-1"


random_background_1=$(ls $directory/* | shuf -n 1)
random_background_2=$(ls $directory/* | shuf -n 1)
# hyprctl hyprpaper unload all
hyprctl hyprpaper preload $random_background_1 > /dev/null
hyprctl hyprpaper preload $random_background_2 > /dev/null
hyprctl hyprpaper wallpaper "$laptop, $random_background_1" > /dev/null
hyprctl hyprpaper wallpaper "$external, $random_background_2" > /dev/null
