#################
### AUTOSTART ###
#################

exec-once = $scripts/waybar_restarter.sh
exec-once = swww-daemon             # Wallpaper
exec-once = miko                    # start notification demon
exec-once = blueman-applet          # bluetooth
exec-once = nm-applet --indicator   # networkmanager
exec-once = udiskie                 # front-end that allows to manage removable media
exec-once = otd-daemon              # opentabletdriver daemon
exec-once = hypridle
exec-once = clipse -listen

### App Launches ###
exec-once = [workspace 1 silent] $webBrowser
exec-once = [workspace 2 silent] code
exec-once = [workspace 3 silent] $terminal
exec-once = [workspace 5 silent] flatpak run io.github.spacingbat3.webcord
exec-once = [workspace 7 silent] $fileManager

### Screen Sharing ###
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

### Authentication Agent ###
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Use gtk-settings
# exec-once = apply-gsettings

# From Gruda
# pre executions (under development)
exec-once = exec xrdb -load ~/.Xresources