####################
### WINDOW RULES ###
####################

### Clipse ###
windowrulev2 = float, class:(clipse)
windowrulev2 = size 622 652, class:(clipse)

### Transparent ###
windowrulev2 = opacity 0.95, class:(Code)

### Float ###
windowrulev2 = float, class:com.nextcloud.desktopclient.nextcloud

### Conky-Sysinfo ###
windowrulev2 = float, class:(Conky-Sysinfo)

# ### Garuda ###
# # windowrule = float, ^(kitty)$
# windowrule = float, ^(garuda-assistant)$
# windowrule = float, ^(garuda-boot-options)$
# windowrule = float, ^(garuda-boot-repair)$
# windowrule = float, ^(garuda-gamer)$
# windowrule = float, ^(garuda-network-assistant)$
# windowrule = float, ^(garuda-settings-manager)$
# windowrule = float, ^(garuda-welcome)$

### Wofi ###
windowrule = stayfocused, ^(wofi)$

### Other ###
windowrulev2 = noblur,class:^()$,title:^()$
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = float, class:(Tk)