#!/usr/bin/env bash

/usr/lib/polkit-kde-authentication-agent-1 &
dunst &             # Notification
picom &             # Compositor
# udiskie -t &        # Disk mounting
# clipse -listen &    # Clipboard manager
powerkit &
icewmbg -f -p --scaled=1 -i ~/nas/share/Pictures/Blue\ Archive/ako-hina.jpg &
deskflow &
